name: CM

on:
  schedule:
    - cron: '0 0 */15 * *'   # 每月的 1、16、31 日 00:00 UTC 触发
  workflow_dispatch:         # 可选：允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run script and save output
        run: |
          python py/CM_Alive.py convert --output all_output.txt
          python py/CM_Alive.py alive CM_Alive.txt --source-file all_output.txt 

      - name: Commit result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CM_Alive.txt
          git commit -m "Auto update CM.txt [skip ci]" || echo "No changes to commit"
          git push
